server:
  port: 8010
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: Alldo527
    database: 2
    timeout: 10000
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        max-wait: -1
        #最大空闲连接
        max-idle: 8
        #最小空闲连接
        min-idle: 1